// data/accommodations.ts
export const accommodationsData = [
    {
      id: 1,
      price: "$5,970",
      title: "Tranquil Haven in the Woods",
      address: "103 Wright Court, Burien, WA 98168",
      beds: 4,
      baths: 3,
      distance: "2.5 Km",
      image: "/hotel.jpg",
    },
    {
      id: 2,
      price: "$1,970",
      title: "Serene Retreat by the Lake",
      address: "1964 Jehovah Drive, VA 22408",
      beds: 3,
      baths: 2,
      distance: "2.5 Km",
      image: "/hotel.jpg",
    },
    {
      id: 3,
      price: "$3,450",
      title: "Charming Cottage in the Meadow",
      address: "1508 Centennial Farm Road, Harlan, 51537",
      beds: 4,
      baths: 4,
      distance: "700 Meter",
      image: "/hotel.jpg",
    },
    {
        id: 4,
        price: "$3,450",
        title: "Charming Cottage in the Meadow",
        address: "1508 Centennial Farm Road, Harlan, 51537",
        beds: 4,
        baths: 4,
        distance: "700 Meter",
        image: "/hotel.jpg",
      },
      {
        id: 5,
        price: "$3,450",
        title: "Charming Cottage in the Meadow",
        address: "1508 Centennial Farm Road, Harlan, 51537",
        beds: 4,
        baths: 4,
        distance: "700 Meter",
        image: "/hotel.jpg",
      },
      {
        id: 6,
        price: "$3,450",
        title: "Charming Cottage in the Meadow",
        address: "1508 Centennial Farm Road, Harlan, 51537",
        beds: 4,
        baths: 4,
        distance: "700 Meter",
        image: "/hotel.jpg",
      },
      {
        id: 7,
        price: "$3,450",
        title: "Charming Cottage in the Meadow",
        address: "1508 Centennial Farm Road, Harlan, 51537",
        beds: 4,
        baths: 4,
        distance: "700 Meter",
        image: "/hotel2.jpg",
      },
      {
        id: 8,
        price: "$3,450",
        title: "Charming Cottage in the Meadow",
        address: "1508 Centennial Farm Road, Harlan, 51537",
        beds: 4,
        baths: 4,
        distance: "700 Meter",
        image: "/hotel2.jpg",
      },
      {
        id: 9,
        price: "$3,450",
        title: "Charming Cottage in the Meadow",
        address: "1508 Centennial Farm Road, Harlan, 51537",
        beds: 4,
        baths: 4,
        distance: "700 Meter",
        image: "/hotel2.jpg",
      },
      {
        id: 10,
        price: "$3,450",
        title: "Charming Cottage in the Meadow",
        address: "1508 Centennial Farm Road, Harlan, 51537",
        beds: 4,
        baths: 4,
        distance: "700 Meter",
        image: "/hotel2.jpg",
      },
      {
        id: 11,
        price: "$3,450",
        title: "Charming Cottage in the Meadow",
        address: "1508 Centennial Farm Road, Harlan, 51537",
        beds: 4,
        baths: 4,
        distance: "700 Meter",
        image: "/hotel2.jpg",
      },
      {
        id: 12,
        price: "$3,450",
        title: "Charming Cottage in the Meadow",
        address: "1508 Centennial Farm Road, Harlan, 51537",
        beds: 4,
        baths: 4,
        distance: "700 Meter",
        image: "/hotel2.jpg",
      },
      {
        id: 13,
        price: "$3,450",
        title: "Charming Cottage in the Meadow",
        address: "1508 Centennial Farm Road, Harlan, 51537",
        beds: 4,
        baths: 4,
        distance: "700 Meter",
        image: "/hotel2.jpg",
      },
  ];
  